SELECT 
P.IDPRODUTO AS CODIGO,
P.DESCRICAOPRODUTO AS DESCRICAO,
P.CODIGONCM AS NCM,
SUM(IT.VALORUNITARIO) AS VALOR_BRUTO,
SUM(IT.SUBTOTAL) AS VALOR_TOTAL_ITEM,
SUM(IT.BASECALCULO) AS BASE_CALCULO,
SUM(IT.PISVALOR) AS VALOR_PIS,
SUM(IT.COFINSVALOR) AS VALOR_COFINS
FROM PRODUTO P
INNER JOIN LFITEMNF IT
ON IT.IDPRODUTO = P.IDPRODUTO
INNER JOIN LFNF NF
ON IT.ID = NF.ID
WHERE NF.DATAMOV BETWEEN '01.02.2025' AND '28.02.2025'
GROUP BY 1,2,3