SELECT
 E.idfilial AS FILIAL,
 E.dataentr AS DATA_ENTRADA,
 E.dataemiss AS DATA_EMISSAO,
 F.nomefornecedor AS FORNECEDOR,
 E.numnota AS NUMERO_NOTA,
 E.valtotnota AS VL_NOTA,
 E.basecalc AS BASE_CALCULO,
SUM( E.valoricms + E.fcpvalor) AS VALOR_ICMS
FROM ENTRADA e
INNER JOIN FORNECEDOR F
ON E.IDFORNECEDOR = F.IDFORNECEDOR
WHERE E.STATUS = 'A'
group by 1,2,3,4,5,6,7

E.DATAENTR = {@DATA_PERIODO} /*DATA ENTRADA*/
E.IDFILIAL = SELECT IDFILIAL, NOMEFILIAL FROM FILIAL = {@SELECT_LISTA} /*FILIAL*/